version: "3.9"
services:
  videoclub:
    build: .
    container_name: videoclub
    ports:
      - "27810:27810"   # expone el puerto, aunque sea consola, lo pide el enunciado
    volumes:
      - ./data:/app/data  # volumen para datos y logs
    environment:
      - DOTNET_ENVIRONMENT=Production
